pipeline {
    agent any
    parameters {
        choice(name: 'ACTION', choices: ['normal'], description: 'Normal Run')
    }
    environment {
        GOOGLE_APPLICATION_CREDENTIALS = credentials('GCP_KEY') // Use the ID from the stored credentials
        SNYK_TOKEN = credentials('SNYK_TOKEN')
        SONARQUBE_ENV = credentials('SONARQUBE_TOKEN')
        PATH = "/opt/sonar-scanner/bin:/usr/local/go/bin:${env.PATH}"
    }
    stages {
        stage('Authenticate with Google Cloud') {
            when {
                expression { params.ACTION == 'deploy-prod' || params.ACTION == 'deploy-staging' }
            }
            steps {
                script {
                    sh 'echo $GOOGLE_APPLICATION_CREDENTIALS > gcloud-key.json'
                    sh '''
                        gcloud auth activate-service-account --key-file=$GOOGLE_APPLICATION_CREDENTIALS
                    '''
                }
            }
        }
        stage('Copy tests into the vm') {
            steps {
                sh 'gcloud compute scp --recurse ./tests performace-test-vm:/home/jenkins/tests --zone europe-west1-b --project dkkom-446515'
            }
        }
    }
}
