pipeline {
    agent any
    parameters {
        choice(name: 'ACTION', choices: ['normal'], description: 'Normal Run')
    }
    environment {
        GOOGLE_APPLICATION_CREDENTIALS = credentials('GCP_KEY') // Use the ID from the stored credentials
        SNYK_TOKEN = credentials('SNYK_TOKEN')
        SONARQUBE_ENV = credentials('SONARQUBE_TOKEN')
        PATH = "/opt/sonar-scanner/bin:/usr/local/go/bin:${env.PATH}"
        JWT_STAGING_TOKEN = credentials('staging-auth-token')
    }
    stages {
        stage('Authenticate with Google Cloud') {
            steps {
                script {
                    sh 'echo $GOOGLE_APPLICATION_CREDENTIALS > gcloud-key.json'
                    sh '''
                        gcloud auth activate-service-account --key-file="$GOOGLE_APPLICATION_CREDENTIALS"
                    '''
                }
            }
        }
        stage('ssh test'){
            steps {
                sh 'gcloud compute ssh performance-test-vm --zone europe-west4-b --project dkkom-446515 --command "export JWT_TOKEN=$JWT_STAGING_TOKEN && echo $JWT_TOKEN"'
            }
        }
        stage('See tests') {
            steps {
                dir('performance-tests') {
                    sh 'ls -la'
                }
            }
        }
        stage('Copy tests into the vm') {
            steps {
                dir('performance-tests') {
                    sh 'gcloud compute scp --recurse ./tests performance-test-vm:/home/jenkins/ --zone europe-west4-b --project dkkom-446515'
                }
            }
        }
    }
}
