FROM gradle:8.10.2-jdk21
WORKDIR /opt/app
COPY ./build/libs/Websocket-gateway-0.0.1-SNAPSHOT.jar ./

EXPOSE 8087

ENTRYPOINT ["sh", "-c", "java ${JAVA_OPTS} -jar Websocket-gateway-0.0.1-SNAPSHOT.jar --spring.profiles.active=test"]