FROM gradle:8.10.2-jdk21
WORKDIR /opt/app
COPY ./build/libs/PermissionsService-0.0.1-SNAPSHOT.jar ./

EXPOSE 8085

ENTRYPOINT ["sh", "-c", "java ${JAVA_OPTS} -jar PermissionsService-0.0.1-SNAPSHOT.jar --spring.profiles.active=test"]