FROM gradle:8.10.2-jdk21
WORKDIR /opt/app
COPY ./build/libs/user-presence-service-0.0.1-SNAPSHOT.jar ./

EXPOSE 8094

ENTRYPOINT ["sh", "-c", "java ${JAVA_OPTS} -jar user-presence-service-0.0.1-SNAPSHOT.jar --spring.profiles.active=test"]