FROM gradle:8.10.2-jdk21
WORKDIR /opt/app
COPY ./build/libs/api_gateway-0.0.1-SNAPSHOT.jar ./

COPY ./src/main/resources/jwt_certs ./jwt_certs

EXPOSE 8080

ENTRYPOINT ["sh", "-c", "java ${JAVA_OPTS} -jar api_gateway-0.0.1-SNAPSHOT.jar --spring.profiles.active=test"]