# -----------------------------------------
# Dockerfile: Run tests at runtime
# -----------------------------------------
FROM gradle:8.10.2-jdk21

# Create a working directory inside the container
WORKDIR /app

# Accept arguments for GitLab credentials
ARG GOOGLE_CLIENT_SECRET

ENV GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}

# Copy Gradle configuration files first for caching
COPY build.gradle settings.gradle ./

# Pre-fetch dependencies to leverage Docker layer caching
RUN gradle --no-daemon dependencies

# Copy the rest of the project (source code, resources, etc.)
COPY . .

# Set the default command to run tests when the container starts
ENTRYPOINT ["gradle", "--no-daemon", "clean", "test"]
